/**
 * Represents the fundamental type of a definition.
 */
export type Primitive =
  | "string"
  | "int"
  | "float"
  | "boolean"
  | "any"
  | "dict"
  | "list";

/**
 * A Definition describes a specific piece of data within the dataflow.
 */
export interface Definition {
  name: string;
  primitive: Primitive;
}

/**
 * An Input is an actual instantiated value bound to a Definition.
 */
export interface Input<T = any> {
  definition: Definition;
  value: T;
}

/**
 * An Operation represents a unit of work. It declares required inputs and outputs,
 * and contains a `run` execution function that can yield data.
 */
export interface Operation<
  In extends Record<string, any> = any,
  Out extends Record<string, any> = any,
> {
  name: string;
  inputs: Record<keyof In, Definition>;
  outputs: Record<keyof Out, Definition>;
  // The executor can return a Promise or be an AsyncGenerator yielding multiple results
  run: (
    args: In,
  ) =>
    | AsyncGenerator<Partial<Out>, void, unknown>
    | Promise<Partial<Out>>
    | Partial<Out>;
}

/**
 * Helper to construct Operations with strict type inference.
 */
export function op<
  In extends Record<string, any>,
  Out extends Record<string, any>,
>(
  config: Operation<In, Out>,
): Operation<In, Out> {
  return config;
}

/**
 * DataFlow encapsulates a network of operations.
 */
export class DataFlow {
  public operations: Operation[] = [];

  constructor(...ops: Operation[]) {
    this.operations = ops;
  }

  static auto(...ops: Operation[]): DataFlow {
    return new DataFlow(...ops);
  }
}

/**
 * A thread-safe(ish) async queue used to manage the event loop of the orchestrator.
 * It allows the orchestrator to go to sleep when waiting for async operations to yield.
 */
class AsyncQueue<T> {
  private items: T[] = [];
  private waiters: ((val: T) => void)[] = [];

  push(val: T) {
    if (this.waiters.length > 0) {
      const resolve = this.waiters.shift();
      if (resolve) resolve(val);
    } else {
      this.items.push(val);
    }
  }

  async pop(): Promise<T> {
    if (this.items.length > 0) {
      return this.items.shift()!;
    }
    return new Promise((resolve) => this.waiters.push(resolve));
  }

  get isEmpty(): boolean {
    return this.items.length === 0;
  }
}

/**
 * Generates all possible combinations of inputs for a given operation.
 * If an Operation needs 'A' and 'B', and we have [A1, A2] and [B1],
 * this returns [{A: A1, B: B1}, {A: A2, B: B1}].
 */
function getCombinations(
  requirements: Record<string, Definition>,
  availableInputs: Map<string, Input[]>,
): Record<string, any>[] {
  const keys = Object.keys(requirements);
  if (keys.length === 0) return [{}]; // No inputs required, runs once with empty args

  const combinations: Record<string, any>[] = [];

  // Recursive combination builder
  function backtrack(idx: number, current: Record<string, any>) {
    if (idx === keys.length) {
      combinations.push({ ...current });
      return;
    }

    const paramName = keys[idx];
    const reqDef = requirements[paramName];
    const inputsForDef = availableInputs.get(reqDef.name) || [];

    for (const input of inputsForDef) {
      current[paramName] = input.value;
      backtrack(idx + 1, current);
    }
  }

  backtrack(0, {});
  return combinations;
}

/**
 * Creates a unique deterministic hash for an execution signature
 * to prevent running the same operation twice with the exact same data.
 */
function hashExecution(opName: string, args: Record<string, any>): string {
  return `${opName}::${JSON.stringify(args, Object.keys(args).sort())}`;
}

/**
 * MemoryOrchestrator resolves dependencies and schedules concurrent executions.
 */
export class MemoryOrchestrator {
  /**
   * Executes the dataflow with the provided seed inputs.
   * Yields outputs as they are generated by the operations.
   */
  async *run(
    dataflow: DataFlow,
    initialInputs: Input[],
  ): AsyncGenerator<Record<string, any>, void, unknown> {
    const stateInputs = new Map<string, Input[]>();
    const executedSignatures = new Set<string>();
    const eventQueue = new AsyncQueue<
      { opName: string; result: Record<string, any> }
    >();

    let activeWorkers = 0;

    // Helper to register new inputs into the state
    const registerInputs = (inputs: Input[]) => {
      for (const input of inputs) {
        const defName = input.definition.name;
        if (!stateInputs.has(defName)) {
          stateInputs.set(defName, []);
        }
        // Avoid pushing duplicate literal values
        const existing = stateInputs.get(defName)!;
        if (
          !existing.some((e) =>
            JSON.stringify(e.value) === JSON.stringify(input.value)
          )
        ) {
          existing.push(input);
        }
      }
    };

    registerInputs(initialInputs);

    // Core orchestration loop
    while (true) {
      let newWorkersStarted = false;

      // 1. Scan all operations to see if any can be triggered
      for (const operation of dataflow.operations) {
        const requiredInputsAvailable = Object.values(operation.inputs).every(
          (def) => (stateInputs.get(def.name)?.length || 0) > 0,
        );

        if (
          requiredInputsAvailable || Object.keys(operation.inputs).length === 0
        ) {
          const possibleArgs = getCombinations(operation.inputs, stateInputs);

          for (const args of possibleArgs) {
            const execHash = hashExecution(operation.name, args);

            // Only run if we haven't processed this exact combination for this operation
            if (!executedSignatures.has(execHash)) {
              executedSignatures.add(execHash);
              activeWorkers++;
              newWorkersStarted = true;

              // Kick off the async operation
              this.executeOperation(operation, args, eventQueue)
                .finally(() => {
                  activeWorkers--;
                  // Push empty event to wake up loop if waiting for workers to close
                  if (activeWorkers === 0) {
                    eventQueue.push({ opName: "SYS_TICK", result: {} });
                  }
                });
            }
          }
        }
      }

      // 2. Check for termination
      if (activeWorkers === 0 && eventQueue.isEmpty && !newWorkersStarted) {
        break;
      }

      // 3. Wait for the next output to be produced
      // If we just started jobs and have no pending events, block until an event comes in.
      if (eventQueue.isEmpty && newWorkersStarted) {
        continue; // Loop around to potentially start more jobs if possible, otherwise block at pop()
      }

      const { opName, result } = await eventQueue.pop();

      // Ignore system ticks
      if (opName === "SYS_TICK") continue;

      // Map plain object results back to strict Inputs based on the operation's output definitions
      const operation = dataflow.operations.find((o) => o.name === opName);
      if (operation) {
        const newInputs: Input[] = [];
        for (const [key, val] of Object.entries(result)) {
          const outDef =
            operation.outputs[key as keyof typeof operation.outputs];
          if (outDef) {
            newInputs.push({ definition: outDef, value: val });
          }
        }

        // Save back to network state
        if (newInputs.length > 0) {
          registerInputs(newInputs);
        }
      }

      // Yield result to consumer
      yield result;
    }
  }

  /**
   * Normalizes the execution of standard functions, Promises, and AsyncGenerators
   */
  private async executeOperation(
    operation: Operation,
    args: Record<string, any>,
    eventQueue: AsyncQueue<any>,
  ) {
    try {
      const rawResult = operation.run(args);

      // Handle Async Generators (yields)
      if (
        rawResult != null && typeof rawResult === "object" &&
        Symbol.asyncIterator in rawResult
      ) {
        const generator = rawResult as AsyncGenerator<Record<string, any>>;
        for await (const yieldedOutput of generator) {
          eventQueue.push({ opName: operation.name, result: yieldedOutput });
        }
      } // Handle Promises / Synchronous objects
      else {
        const resolvedOutput = await rawResult;
        if (resolvedOutput) {
          eventQueue.push({ opName: operation.name, result: resolvedOutput });
        }
      }
    } catch (err) {
      console.error(
        `[DataFlow Error] Operation '${operation.name}' failed:`,
        err,
      );
      throw err;
    }
  }
}

// ---------------------------------------------------------
// USAGE EXAMPLE & TEST CASES
// (Replicating the logic from the Python TestCase provided)
// ---------------------------------------------------------

const CountStart: Definition = { name: "count_start", primitive: "int" };
const Count: Definition = { name: "count", primitive: "int" };
const NumberDef: Definition = { name: "number", primitive: "int" };

// Operation: Generator that emits 5 numbers starting from count_start
const counter = op<{ count_start: number }, { count: number }>({
  name: "counter",
  inputs: { count_start: CountStart },
  outputs: { count: Count },
  run: async function* (args) {
    const start = args.count_start;
    for (let i = start; i < start + 5; i++) {
      // Emulate asynchronous yielding
      await new Promise((res) => setTimeout(res, 50));
      yield { count: i };
    }
  },
});

// Operation: Generator that auto-starts without inputs
const counterAutoStart = op<{}, { count: number }>({
  name: "counter_auto_start",
  inputs: {},
  outputs: { count: Count },
  run: async function* () {
    for (let i = 0; i < 5; i++) {
      await new Promise((res) => setTimeout(res, 50));
      yield { count: i };
    }
  },
});

// Operation: Takes a count and simply echoes it out as a Number
const echoNum = op<{ number_in: number }, { number_out: number }>({
  name: "echo_num",
  inputs: { number_in: Count },
  outputs: { number_out: NumberDef },
  run: async (args) => {
    return { number_out: args.number_in };
  },
});

// Run Tests Immediately
(async function runTests() {
  console.log("=== Starting DataFlow Orchestration Tests ===\n");

  const orchestrator = new MemoryOrchestrator();

  // ---------------------------------------------------------
  // Test 1: Generator with Input
  // ---------------------------------------------------------
  console.log("-> Running test_gen_with_input...");
  const testDataflow1 = DataFlow.auto(counter, echoNum);

  const initialInputs1: Input[] = [
    { definition: CountStart, value: 1 },
  ];

  const results1: number[] = [];

  // Subscribe to orchestrator results
  for await (const result of orchestrator.run(testDataflow1, initialInputs1)) {
    // Look for outputs bound to our "echoNum" operation
    if ("number_out" in result) {
      results1.push(result.number_out);
      console.log(`   Received number_out: ${result.number_out}`);
    }
  }

  console.log(`   Test 1 Result Array: [${results1.join(", ")}]`);
  console.assert(
    JSON.stringify(results1.sort()) === JSON.stringify([1, 2, 3, 4, 5]),
    "Test 1 Failed",
  );
  console.log("   ✅ Test 1 Passed\n");

  // ---------------------------------------------------------
  // Test 2: Generator with Auto Start
  // ---------------------------------------------------------
  console.log("-> Running test_gen_auto_start...");
  const testDataflow2 = DataFlow.auto(counterAutoStart, echoNum);

  const results2: number[] = [];

  for await (const result of orchestrator.run(testDataflow2, [])) { // Auto-start uses empty inputs
    if ("number_out" in result) {
      results2.push(result.number_out);
      console.log(`   Received number_out: ${result.number_out}`);
    }
  }

  console.log(`   Test 2 Result Array: [${results2.join(", ")}]`);
  console.assert(
    JSON.stringify(results2.sort()) === JSON.stringify([0, 1, 2, 3, 4]),
    "Test 2 Failed",
  );
  console.log("   ✅ Test 2 Passed\n");
})();
